### ISSUE TITLE
Add intelliJ idea 2019

### ISSUE THREAD

**Issue by sgsh-gh** [Homebrew/homebrew-cask-versions#10072]
Some plugins doesn't support new version of intelliJ. I'd like to add option to install old version

**Comment by sgsh-gh** [comment]
```
cask 'intellij-idea19' do
  version '2019.3.4'
  sha256 '754793f12973c1e78688a4865a43928dcbd3a10c6b2c40522f8337bb10153023'

  url "https://download.jetbrains.com/idea/ideaIU-#{version}.dmg"
  appcast 'https://data.services.jetbrains.com/products/releases?code=IIU&latest=false&type=release'
  name 'IntelliJ IDEA Ultimate'
  homepage 'https://www.jetbrains.com/idea/'

  auto_updates true

  app 'IntelliJ IDEA.app'

  uninstall_postflight do
    ENV['PATH'].split(File::PATH_SEPARATOR).map { |path| File.join(path, 'idea') }.each { |path| File.delete(path) if File.exist?(path) && File.readlines(path).grep(%r{# see com.intellij.idea.SocketLock for the server side of this interface}).any? }
  end

  zap trash: [
               '~/Library/Preferences/com.jetbrains.intellij.plist',
               "~/Library/Caches/IntelliJIdea#{version.major_minor}",
               "~/Library/Logs/IntelliJIdea#{version.major_minor}",
               "~/Library/Application Support/IntelliJIdea#{version.major_minor}",
               "~/Library/Preferences/IntelliJIdea#{version.major_minor}",
               '~/Library/Saved Application State/com.jetbrains.intellij.savedState',
             ]
end
```
I copied from # Copied from https://github.com/Homebrew/homebrew-cask/blame/64b21e2066c92c5b8c4c6259dbe88e897bd3396d/Casks/intellij-idea.rb and update cask name and url parameter. I'll create PR later.

**Comment by sgsh-gh** [comment]
> homebrew/cask-versions is not intended to be used for all and any old versions you personally require. Casks submitted here should be expected to be used by a reasonable number of people and supported by contributors long-term.
> - Legacy versions of gratis or open-source software that were accepted should be removed after one year.

I'm wondering if my request is satisfying the requirements. Every intelliJ updates, several plugins doesn't support so that we need wait at most 1 year. So having 1 old version is helpful, isn't it?

**Comment by miccal** [comment]
I think this would be fine to add -- please feel free to submit a PR.

**Comment by sgsh-gh** [comment]
I opened #10080
