### ISSUE TITLE
 Firefox Developer Edition download links have changed

### ISSUE THREAD

**Issue by tpkahlon** [Homebrew/homebrew-cask-versions#10304]
-  Firefox Developer Edition download links have changed
- Older issue is linked to #4090

**Comment by miccal** [comment]
The current `url` seems correct, and I tested it for several different languages:
```
|-> brew fetch firefox-developer-edition
==> Downloading https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=osx&lang=en-US
==> Downloading from https://download-installer.cdn.mozilla.net/pub/devedition/releases/86.0b3/mac/en-US/Firefox%2086.0b3.dmg
######################################################################## 100.0%
Downloaded to: /Users/miccal/Library/Caches/Homebrew/downloads/382608000536d61f64e4a147e764c559ce144c3f04dd0f05209549d3bf118f1a--Firefox 86.0b3.dmg
SHA256: 493e5568a5b527ae352e56fe5cc353e999c9561162bc513b58a7b03338f290f9
Warning: No checksum defined for cask 'firefox-developer-edition', skipping verification.
```

**Comment by tpkahlon** [comment]
See [this](https://ibb.co/NZ3bdmD). Is there something I'm missing?

**Comment by miccal** [comment]
Try running `brew tap homebrew/cask-versions` first.

**Comment by vitorgalvao** [comment]
@tpkahlon Next time, please don’t ignore the issue template. Had you followed it, we’d have saved maintainer time and solved your question three days ago.

**Comment by tpkahlon** [comment]
@vitorgalvao Agreed. It was a shortsighted approach on my end. I'll make sure future requests follow issue template guideline.
