### ISSUE TITLE
brew install sublime-text-dev doesn't work

### ISSUE THREAD

**Issue by tabchas** [Homebrew/homebrew-cask-versions#11332]
### 

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

### Description of issue

`brew install sublime-text-dev` doesn't seem to work

### Command that failed

brew install sublime-text-dev

### Output of command with `--verbose --debug`

<details><summary>Click to expand</summary><pre><code>

==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/3.2.0-126-g83aa3ff\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.4\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location https://api.github.com/search/code\?q=user\%3AHomebrew\+path\%3AFormula\+path\%3ACasks\+path\%3A.\+filename\%3Asublime-text-dev\+extension\%3Arb\&per_page=100 --header Accept:\ application/vnd.github.v3\+json --write-out '
'\%\{http_code\} --header Accept:\ application/vnd.github.antiope-preview\+json --dump-header /private/tmp/github_api_headers20210703-9630-1ydpotb
Error: No formulae found in taps.

</code></pre></details>

### Output of `brew tap`

<details><summary>Click to expand</summary><pre><code>

armmbed/formulae
homebrew/cask
homebrew/cask-drivers
homebrew/core
homebrew/services

</code></pre></details>

**Comment by bevanjkay** [comment]
It looks like you don't have homebrew-cask-versions

Try running the following command in your terminal and then run the install again
` brew tap homebrew/cask-versions`
