### ISSUE TITLE
Missing mac silicon binary of latest temurin 17

### ISSUE THREAD

**Issue by ogr3** [Homebrew/homebrew-cask-versions#14974]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

Brew upgrade tries to upgrade temurin cast to 17.0.5,8, but that version is not uploaded to temurin repo for mac silicon

### Command that failed

brew upgrade

### Output of command with `--verbose --debug`

```shell
==> Upgrading temurin17
==> Downloading https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.5%2B8/OpenJDK17U-jdk_aarch64_mac_hotspot_17.0.5_8.pkg
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.7-32-g31758ea\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6\)\ curl/7.79.1 --header Accept-Language:\ en --fail --retry 3 --location --remote-time --output /Users/fredrik.duprez/Library/Caches/Homebrew/downloads/38c9d81655397fb34636ce67ea4368cdf9a8545eb58d3a887a961676947c4099--OpenJDK17U-jdk_aarch64_mac_hotspot_17.0.5_8.pkg.incomplete https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.5\%2B8/OpenJDK17U-jdk_aarch64_mac_hotspot_17.0.5_8.pkg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
==> Purging files for version 17.0.5,8 of Cask temurin17
Error: temurin17: Download failed on Cask 'temurin17' with message: Download failed: https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.5%2B8/OpenJDK17U-jdk_aarch64_mac_hotspot_17.0.5_8.pkg
```

### Output of `brew doctor --verbose`

```shell
==> Homebrew Version
3.6.7-32-g31758ea
==> macOS
12.6
==> SIP
Enabled
==> Homebrew Cask Staging Location
/opt/homebrew/Caskroom
==> Homebrew Cask Taps:
/opt/homebrew/Library/Taps/homebrew/homebrew-cask (4106 casks)
/opt/homebrew/Library/Taps/homebrew/homebrew-cask-versions (230 casks)
```

### Output of `brew tap`

```shell
homebrew/cask
homebrew/cask-versions
homebrew/core
```

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask-versions/pull/14976
