### ISSUE TITLE
whatsapp-beta cask incorrect for Apple Silicon

### ISSUE THREAD

**Issue by alex-ioma** [Homebrew/homebrew-cask-versions#17513]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

When trying to install whatsapp-beta from this tap the version of whatsapp beta is incorrect if you are running a mac with Apple Silicon. I cannot confirm if that applies also to Intel mac and the beta channel has changed location since I did not check. 

This is how the formula might be: 

```ruby
cask "whatsapp-beta-native" do
  version "2.23.17.75"
  sha256 :no_check

  url "https://web.whatsapp.com/desktop-beta/mac_native/release... or similar"
  name "WhatsApp"
  desc "Desktop client for WhatsApp"
  homepage "https://www.whatsapp.com/"

  livecheck do
    url "https://web.whatsapp.com/desktop-beta/mac_native/releases... or similar"
    strategy :json do |json|
      json["name"]
    end
  end

  auto_updates true
  conflicts_with cask: [
    "whatsapp",
    "whatsapp-alpha",
    "whatsapp-beta",
  ]

  app "WhatsApp.app"

  zap trash: [
    "~/Library/Application Scripts/net.whatsapp.WhatsApp",
    "~/Library/Application Scripts/net.whatsapp.WhatsApp.Intents",
    "~/Library/Application Scripts/net.whatsapp.WhatsApp.IntentsUI",
    "~/Library/Application Scripts/net.whatsapp.WhatsApp.ServiceExtension",
    "~/Library/Caches/net.whatsapp.WhatsApp",
    "~/Library/Containers/net.whatsapp.WhatsApp",
    "~/Library/Containers/net.whatsapp.WhatsApp.Intents",
    "~/Library/Containers/net.whatsapp.WhatsApp.ServiceExtension",
    "~/Library/Group Containers/group.com.facebook.family",
    "~/Library/Group Containers/group.net.whatsapp.family",
    "~/Library/Group Containers/group.net.whatsapp.WhatsApp.private",
    "~/Library/Group Containers/group.net.whatsapp.WhatsApp.shared",
    "~/Library/Group Containers/group.net.whatsapp.WhatsAppSMB.shared",
    "~/Library/Saved Application State/net.whatsapp.WhatsApp.savedState",
  ]
end
```

A few doubts: 
- Not sure about the correct url for the dmg file
- Not sure if this cask should be a different cask or replace the current beta
- Not sure if `~/Library/Group Containers/group.com.facebook.family` should be zapped

Apologies if this is not the right way to report this - I wasn't sure how to properly create a pull request. 

Thanks.

### Command that failed

brew install --cask whatsapp-beta

### Output of command with `--verbose --debug`

```shell
Program installed correctly but is not the latest WhatsApp Beta app for Mac Apple Silicon.
```

### Output of `brew doctor` and `brew config`

```shell
Not relevant.
```

### Output of `brew tap`

```shell
Not relevant.
```

**Comment by bevanjkay** [comment]
I think you're looking for the `whatsapp-alpha` cask, which links to the new "native" version of whatsapp which is a different branch to the beta of the standard `whatsapp` cask.

**Comment by alex-ioma** [comment]
Thanks @bevanjkay, you are right! That is the "native beta".

However, by looking at the formula, it looks like the zap sections should be updated. I've just installed the app form the dmg file and the files it creates are as reported in my original posts (cross-checked with AppCleaner).

Would you be able to create a merge request with the updated section or should I?

**Comment by bevanjkay** [comment]
Feel free to open a PR to update the zap for the `whatsapp-alpha` cask 👍🏻
