### ISSUE TITLE
Add new corretto21 distribution of OpenJDK 21 LTS

### ISSUE THREAD

**Issue by GoKuroko** [Homebrew/homebrew-cask-versions#17831]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

As all we known, JDK21 has become the next long-term support version. So, people may expect to stay in the LTS version instead of an unpredictable cask that keeps scrolling every half-year.

Hope you can approve the corretto21's pull request. #17823

### Command that failed

brew install --cask corretto21 

### Output of command with `--verbose --debug`

```shell
Not relevant.
```

### Output of `brew doctor` and `brew config`

```shell
Not relevant.
```

### Output of `brew tap`

```shell
Not relevant.
```

**Comment by miccal** [comment]
Version 21 of Amazon Corretto is available in the main `homebrew-cask` repository. Once version 22 is released, the version in the main repository will be updated to version 22 and only then we can add version 21 to the `homebrew-cask`versions` repository.

**Comment by GoKuroko** [comment]
However, the Zulu21 has been merged to the `homebrew-cask-version` repository. I think this doesn't conform to the rules you described. #17757 @miccal 

https://github.com/Homebrew/homebrew-cask-versions/blob/master/Casks/zulu21.rb
https://github.com/Homebrew/homebrew-cask/blob/master/Casks/z/zulu.rb

**Comment by miccal** [comment]
Adding `zulu21` was an error -- Casks in the `homebrew-cask-versions` repository should not in general match those in the main `homebrew-cask` repository.
