### ISSUE TITLE
wine-staging version is very old (was not updated when wine-devel was updated to 8.17)

### ISSUE THREAD

**Issue by rxhfcy** [Homebrew/homebrew-cask-versions#17962]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

wine-devel was [recently updated from 8.10 to 8.17](https://github.com/Homebrew/homebrew-cask-versions/commit/972c5be7e87b57838144970889b3968c82ebd948) by @hannesbraun (great!) but...

...however, **wine-staging** was _not_ updated, so the current wine-staging version is still very old (8.10)

Suggestion: please update wine-staging too? (because some applications require wine-staging)

The newest version of wine-staging is 8.17.1 (wine-staging-8.17.1-osx64.tar.xz):
https://github.com/Gcenx/macOS_Wine_builds/releases/tag/8.17

(the old wine-staging 8.10 is over 3 months old)
https://github.com/Homebrew/homebrew-cask-versions/blob/master/Casks/wine-staging.rb

### Command that failed

Not relevant.

### Output of command with `--verbose --debug`

```shell
Not relevant.
```

### Output of `brew doctor` and `brew config`

```shell
Not relevant.
```

### Output of `brew tap`

```shell
Not relevant.
```

**Comment by hannesbraun** [comment]
This should be fixed with #17963
