### ISSUE TITLE
wine-devel and wine-staging: `wine`: command not found (`wine64` works fine)

### ISSUE THREAD

**Issue by rxhfcy** [Homebrew/homebrew-cask-versions#18739]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

The following applies to both wine-devel and wine-staging (9.0-rc2, latest version)

Running `$ wine` doesn't work (`wine64` works fine though).
```
$ wine
-bash: wine: command not found
```

Also: running `$ wine64` alone only mentions using "wine", not "wine64", so `wine` probably should work as well (i.e. should't show an error message):

```
$ wine64
Usage: wine PROGRAM [ARGUMENTS...]   Run the specified program
       wine --help                   Display this help and exit
       wine --version                Output version information and exit
$
$ wine --help
-bash: wine: command not found
$
$ wine --version
-bash: wine: command not found
```

### Command that failed

wine

### Output of command with `--verbose --debug`

```shell
-bash: wine: command not found
```

### Output of `brew doctor` and `brew config`

```shell
Not relevant.

(brew doctor said "Your system is ready to brew."
and brew config looked normal to me, macOS: 14.2-arm64, HOMEBREW_VERSION: 4.2.0)
```

### Output of `brew tap`

```shell
Not relevant.

(it did include homebrew/cask-versions)
```

**Comment by miccal** [comment]
Ping @Gcenx
