### ISSUE TITLE
Tower version 2 - can it be considered?

### ISSUE THREAD

**Issue by edrozenberg** [Homebrew/homebrew-cask-versions#5874]
#### General troubleshooting steps

- [ ] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Tower.app (git client) recently updated from v2 to v3. v3 forces a subscription model, instead of a regular purchased software license.

There is enough negative feeling about this by various folks that having a v2 install option would be nice for those of us who want the option to continue using v2.

I can look at doing a PR if v2 would be considered.

For reference, the place to access the v2 downloads:
https://www.git-tower.com/release-notes/mac
https://www.git-tower.com/download-TO2M

#### Command that failed

```
{{replace this}}
```

#### Output of command with `--force --verbose --debug`

```
{{replace this}}
```

#### Output of `brew cask doctor`

```
{{replace this}}
```

#### Output of `brew tap`

```
{{replace this}}
```

**Comment by reitermarkus** [comment]
> There is enough negative feeling about this by various folks 

I share the feeling, I won't be “upgrading” to the subscription model. Feel free to submit a PR.

**Comment by vitorgalvao** [comment]
I’m not a Tower user, but as far as I’m concerned, when a piece of software changes to a subscription model, I wouldn’t mind having the non-subscription here indefinitely, provided it’s used by a reasonable number of people or at least one maintainer, and it still works in the current macOS.

Go ahead with the PR.
