### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by revolter** [Homebrew/homebrew-cask-versions#5926]
I don't understand how to use this tap. Mainly, searching for available older versions and picking one. The README only features `iterm-beta` as an example but I'd want for example to install Unity `2018.1.4f1` instead of the latest `2018.1.6` and I don't know how to do that.

**Comment by vitorgalvao** [comment]
> but I'd want for example to install Unity `2018.1.4f1` instead of the latest `2018.1.6` and I don't know how to do that.

That’s not something you’ll find here. We don’t provide every old version, only [a specific useful subset](https://github.com/Homebrew/homebrew-cask-versions#acceptable-casks). Do `brew search unity` as usual. If there are older versions, you’ll see the version number in the name. Example: searching for `alfred` yields `alfred` and `alfred2`.

**Comment by revolter** [comment]
So it doesn't provide previously submitted (via PR) versions? Meaning older `.rb` files with their _possible_ old URLs?

**Comment by commitay** [comment]
> 2. Instead of requiring manually created `.rb` files that point to _some_ versions, it would rely on older versions in `git` that were already created.

This was implemented with Homebrew formulae  _and removed_ because it caused too many problems. Casks would still have similar issue.

**Comment by commitay** [comment]
For legacy versions of Unity this tap may be of interest. 

https://github.com/wooga/homebrew-unityversions

**Comment by revolter** [comment]
> This was implemented with Homebrew formulae

`Manually` could also be replaced with `a separate manual action` _(as opposed to an automatic flow)_

> it caused too many problems

Related to their dependencies? As they too should have been downgraded.

**Comment by revolter** [comment]
> For legacy versions of Unity this tap may be of interest.
>
> https://github.com/wooga/homebrew-unityversions

So it isn't possible to have this feature automatically working by replacing separate `.rb` files with separate versions of the same `.rb` file from `git log`?

**Comment by commitay** [comment]
No, we won't add it as a feature as we don't indent to support installing old versions via git history.

We support the casks currently exist on master branch.

**Comment by revolter** [comment]
If it's not too much (in which case, disregard this message), could you please tell me why is this something you guys don't want to add? As I can't see any disadvantage with my very limited knowledge about Homebrew's internals.

**Comment by vitorgalvao** [comment]
You’re free to install casks from specific git revision URLs (that works), but that will never be supported. For one, since those are fixed it’s impossible to retroactively fix an old version cask. That alone already makes a maintenance burden not worth supporting.

**Comment by commitay** [comment]
> > That alone already makes a maintenance burden not worth supporting.

> So there is no maintainance required at all.

The maintainers (who have to deal with any problems) decide if it's a maintenance burden or not. This has been suggested several times before and whatever benefit it offers does not outweigh the problems that comes with it.

**Comment by revolter** [comment]
And what would be the problem? If any problem that may arrise will be reported in terminal with an error message?

**Comment by commitay** [comment]
Just one example of a problem would be  if `A 3` installs malware or otherwise breaks the users system? We would need to somehow prevent users from installing that specific version from the history?

**Comment by revolter** [comment]
I see, thank you for the example. I'm thinking of creating a plugin (if Homebrew supports it, gotta do some research) that adds this feature, knowing that this is not something that's wanted as a first party support, and I guess I'll just print something like "Older versions might contain malware or may break your system. Install them at your own risk" and that's it ¯\_(ツ)_/¯.

Thank you again for your time.

**Comment by vitorgalvao** [comment]
> Meaning `brew cask install unity https://raw.githubusercontent.com/Homebrew/homebrew-cask/fb8aff1ec1dda9057ce8514a5df70c9b186b6a61/Casks/unity.rb`?

No, just `brew cask install https://raw.githubusercontent.com/Homebrew/homebrew-cask/fb8aff1ec1dda9057ce8514a5df70c9b186b6a61/Casks/unity.rb`. Basically we can install casks (if they’re valid) from a URL.

> By "fixed" do you mean when the `cask` API changes?

No, I mean if the cask has a mistake (like a bad `uninstall`). This might not even be a mistake we made, but simply something that changed because upstream changed how it was done.

> So there is no maintainance required at all.

Sure there is. When people start opening issues because those casks are broken. That *will* (would) happen and there‘s no point telling people to not open issues related to that, they still would.

> I'm thinking of creating a plugin

Go for it! Just know it’ll not be officially sanctioned, and please please do mention that in your README.

Also, before you start any work, think about what you’ll do about casks that are versioned but have unversioned URLs. Those will never work under your system.
