### ISSUE TITLE
PR template refers to stable version

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/homebrew-cask-versions#6056]
regression introdced in commit 461e1b7a6e57f7df1a7983d14d2871b6e5136bf6

**Comment by vitorgalvao** [comment]
It refers to stable version *or* documented exception, which this repo falls into.

**Comment by yurikoles** [comment]
@vitorgalvao the mentioned exception is for app with no stable version. Unstable casks are described in another section. The main issue is that this text confuses users that try to submit unstable cask. In fact, it should state opposite: `this is unstable version, stable casks go here =>`

**Comment by vitorgalvao** [comment]
That box is an experiment, anyway, and may soon be removed. I doubt users are going to be confused by it. The point is that in this repo you shouldn’t tick that box.
