### ISSUE TITLE
Question about adding a cask for PowerShell 6.0

### ISSUE THREAD

**Issue by TravisEz13** [Homebrew/homebrew-cask-versions#6284]
PowerShell 6.0 will be supported until 2/13/2019.  Our main cask installs, PowerShell 6.1.  I have had a few people ask me how they install 6.0 using brew.  I was thinking of creating a `powershell-servicing` cask for the oldest viable servicing release.  Is this allowed?  I'm happy to maintain it.

One issues, it cannot be installed Side-By-Side with the PowerShell cask (unless I rewrite to use our `tar.gz` instead of the `pkg`).  Is there a way of declaring this?

Another issue, I'm not sure of the naming convention for these type of casks. I don't want to call it `powershell-6.0` as that would only work for a while. 

I have two names I'm considering:

* `powershell-servicing` servicing is what we call our releases which are older than our current stable.
* `powershell-slow` indicating that we won't move to the new stable until required to (i.e. slowly.)

There will probably be some time after 6.0 EOLs, that `powershell` and `powershell-servicing` install the same thing, but I don't think this is an issue.

**Comment by reitermarkus** [comment]
> PowerShell 6.0 will be supported until 2/13/2018.

Do you mean 2019 here?

> it cannot be installed Side-By-Side with the PowerShell cask

You can add `conflicts_with`.

> unless I rewrite to use our `tar.gz` instead of the `pkg`

Does the `.tar.gz` install a binary? Preferably `powershell` should be a Formula and be built from source since it is open-source and CLI-only.

> I have two names I'm considering:

This would have to be called `powershell60` according to our current naming convention, unless this is actually documented upstream as a separate release channel.

**Comment by vitorgalvao** [comment]
> You can add `conflicts_with`.

`conflict_with` isn’t yet functional, and is just a stub. That’s generally fine as we add it to `app` casks, but on a `pkg` cask it might lead to nasty surprises.

> Preferably `powershell` should be a Formula and be built from source since it is open-source and CLI-only.

But yes, this should be the case anyway.

**Comment by commitay** [comment]
> `conflict_with` isn’t yet functional, and is just a stub.

`conflicts_with cask` has been implemented. https://github.com/Homebrew/brew/pull/3001

**Comment by vitorgalvao** [comment]
> `conflicts_with cask` has been implemented. [Homebrew/brew#3001](https://github.com/Homebrew/brew/pull/3001)

I didn’t remember that at all (but clearly knew about it, since I was pinged). We should fix the documentation in that regard. It was recently when I thought “wait a minute, did we ever end up implementing `conflicts_with` that I searched for it in the docs and found it still referred as a stub”.

**Comment by TravisEz13** [comment]
Build PowerShell is complicated and currently requires PowerShell (to pull in PowerShell modules that are required to make the language usable.)  Switching to be a formula would be difficult and requires hundreds of megabytes of dependencies.  We have long term goals to address these issue, but for the immediate future I think it needs to remain a cask.

I'm fine with `powershell60` as long as we are okay with it having ~6 month life.  

Thanks, for your help:

```ruby
cask 'powershell60' do
  version '6.0.4'
  sha256 '0c59ff0fcacc957342012f44fcb8db255fd05babd081455edb2648566e2b29cc'

  url "https://github.com/PowerShell/PowerShell/releases/download/v#{version}/powershell-#{version}-osx.10.12-x64.pkg"
  appcast 'https://github.com/PowerShell/PowerShell/releases.atom'
  name 'PowerShell'
  homepage 'https://github.com/PowerShell/PowerShell'

  depends_on formula: 'openssl'
  depends_on macos: '>= :sierra'

  pkg "powershell-#{version}-osx.10.12-x64.pkg"

  uninstall pkgutil: 'com.microsoft.powershell'

  zap trash: [
               '~/.cache/powershell',
               '~/.config/PowerShell',
               '~/.local/share/powershell',
             ],
      rmdir: [
               '~/.cache',
               '~/.config',
               '~/.local/share',
               '~/.local',
             ]

  conflicts_with cask: 'powershell'

  caveats <<~EOS
    A OpenSSL-backed libcurl with GSSAPI is required for custom handling
    of certificates and default credentials for web requests.
    This is rarely needed, but you can install it with
      brew install curl --with-openssl --with-gssapi
    See https://github.com/PowerShell/PowerShell/issues/5638
  EOS
end
```

**Comment by TravisEz13** [comment]
I submitted a PR to add this:  https://github.com/Homebrew/homebrew-cask-versions/pull/6294

**Comment by commitay** [comment]
Closed via https://github.com/Homebrew/homebrew-cask-versions/pull/6294
