### ISSUE TITLE
Unable to find micrsoft-remote-desktop-beta

### ISSUE THREAD

**Issue by Jarli01** [Homebrew/homebrew-cask-versions#6447]
While attempting to install ```microsoft-remote-desktop-beta``` the installation fails with "cannot find any casks with this name" Yet . . . https://github.com/Homebrew/homebrew-cask-versions/blob/master/Casks/microsoft-remote-desktop-beta.rb

What am I missing here as other casks work without any additional processing?

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.
