### ISSUE TITLE
Cask 'java6' confusing naming scheme

### ISSUE THREAD

**Issue by robertleeblairjr** [Homebrew/homebrew-cask-versions#7611]
Not really a bug or major issue but I was curious as to if a cask name can be changed so as to differentiate it from other casks when issuing 'brew search {string}'. For example 'java6' is referencing the Apple supplied version of Java 1.6 on their support site. But, the other casks with 'java{#}' refer to OpenJDK. Of course, this may not be as easy as merely renaming the cask name 'java6' -> 'apple-java' or 'apple-java6'. Plus, it being a fairly outdated package for older OS X versions, then it may not be worth the hassle. Either way, it was just a thought.

**Comment by vitorgalvao** [comment]
[Java casks are getting a revamp](https://github.com/Homebrew/homebrew-cask/issues/57387).

**Comment by robertleeblairjr** [comment]
> [Java casks are getting a revamp](https://github.com/Homebrew/homebrew-cask/issues/57387).

Thanks for the link. That is yet another post I've not come across yet but I've seen many others thus far. Hopefully, there's a consensus for what's included/removed in which taps and the tokens associated with them. I wonder if there's a tool which could be implemented by homebrew which would allow scanning existing taps or as they're added for any name conflict, regardless of installed locally, and throwing a warning for it. Since the homebrew tap is required prior to adding additional taps then it would be a pretty nice feature. I suppose the same could be said of any project that forks which could scan to determine if their casks have any existing/future name conflicts with homebrew official taps.
