### ISSUE TITLE
Can't download Edge Canary

### ISSUE THREAD

**Issue by mindrones** [Homebrew/homebrew-cask-versions#7623]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Can't fetch the the pkg. I got:

```
==> Satisfying dependencies
==> Downloading https://officecdn-microsoft-com.akamaized.net/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/MicrosoftEdgeCanary-77.0.218.0.pkg

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'microsoft-edge-canary' with message: Download failed: https://officecdn-microsoft-com.akamaized.net/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/MicrosoftEdgeCanary-77.0.218.0.pkg
```

#### Command that failed

```
brew cask install microsoft-edge-canary
```

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.

**Comment by mindrones** [comment]
Running 

`brew cask fetch microsoft-edge-canary`

before 

`brew cask install microsoft-edge-canary`

seems to have fixed it, thanks @robertleeblairjr! 👍
