### ISSUE TITLE
Installing microsoft-edge-canary may fail due to appcast string parsing

### ISSUE THREAD

**Issue by coreygo** [Homebrew/homebrew-cask-versions#7778]
#### General troubleshooting steps

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

[Casks/microsoft-edge-canary.rb#L6-L7](https://github.com/Homebrew/homebrew-cask-versions/blob/19606ec9561d062c79e444b69476ad5a859b5c3a/Casks/microsoft-edge-canary.rb#L6-L7) does not correctly parse the appcast file `0409EDCN01-chk.xml`.

The `.0` is hardcoded so if the version is `<string>78.250.1908191</string>` the download will fail—`MicrosoftEdgeCanary-78.0.250.0.pkg` is 404. I'm uncertain if Microsoft uses the first or last digit from the patch semver when releasing new packages. I'm guessing they truncate to the first digit but I could be wrong and haven't been installing Canary builds to notice a trend.

The correct URL is currently: `https://officecdn-microsoft-com.akamaized.net/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/MicrosoftEdgeCanary-78.0.250.1.pkg`

I was going to update this cask to include a `zap` but hit this bug. Requesting input on best practice to resolve URL parsing.

#### Command that failed

```
brew cask install microsoft-edge-canary
```

#### Output of command with `--force --verbose --debug`
<details><summary>$ brew cask install microsoft-edge-canary --force --verbose --debug</summary>
<p>

```
$ brew cask install microsoft-edge-canary --force --verbose --debug
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
/usr/local/opt/curl/bin/curl -q --show-error --user-agent Homebrew/2.1.10-30-g84c5f40\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.6\)\ curl/7.65.3 --location --silent --head --request GET https://officecdn-microsoft-com.akamaized.net/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/MicrosoftEdgeCanary-78.0.250.0.pkg
==> Downloading https://officecdn-microsoft-com.akamaized.net/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/MicrosoftEdgeCanary-78.0.250.0.pkg
/usr/local/opt/curl/bin/curl -q --show-error --user-agent Homebrew/2.1.10-30-g84c5f40\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.6\)\ curl/7.65.3 --location --range 0-1 --dump-header - --write-out \%\{http_code\} --output /dev/null https://officecdn-microsoft-com.akamaized.net/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/MicrosoftEdgeCanary-78.0.250.0.pkg
/usr/local/opt/curl/bin/curl -q --show-error --user-agent Homebrew/2.1.10-30-g84c5f40\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.6\)\ curl/7.65.3 --fail --location --remote-time --continue-at 0 --output /Users/corey/Library/Caches/Homebrew/downloads/0a846a3e4fc8c57fa186d2d15587e88898282882aaee0d6d1aa354c3e15f81b3--MicrosoftEdgeCanary-78.0.250.0.pkg.incomplete https://officecdn-microsoft-com.akamaized.net/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/MicrosoftEdgeCanary-78.0.250.0.pkg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'microsoft-edge-canary' with message: Download failed: https://officecdn-microsoft-com.akamaized.net/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/MicrosoftEdgeCanary-78.0.250.0.pkg
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:311:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:308:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:42:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:20:in `perform'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:149:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:66:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:94:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:23:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:93:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:159:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:124:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:163:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:163:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:147:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:124:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

</p>
</details>

**Comment by coreygo** [comment]
Pinged [MSEdgeDev on Twitter](https://twitter.com/coreygouker/status/1163909735415894016), hopefully they can provide quick clarification.

**Comment by coreygo** [comment]
I didn't receive a response via Twitter so pinged the Microsoft Edge Support email. One of the people at that alias is waiting for an Edge SWE to respond and should hopefully provide details next week.

However, looking at the XML today, it appears the version is `<string>78.254.1908210</string>` so the About Microsoft Edge Version displays as `78.0.254.0` and the package URL is:
`https://officecdn-microsoft-com.akamaized.net/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/MicrosoftEdgeCanary-78.0.254.0.pkg`

Which implies that Microsoft uses the _last digit of the patch semver_.

**Comment by vitorgalvao** [comment]
@coreygo It occurred to me that sometime in the future someone may find that piece of code and try to improve it (breaking it in the process) because they may see the specificity of removing the six digits as an error. Would you mind adding a comment to the casks to the effect of `Parsing logic clarified by vendor: https://github.com/Homebrew/homebrew-cask-versions/issues/7778#issuecomment-525870763`?
