### ISSUE TITLE
Info on unversioned Firefox casks

### ISSUE THREAD

**Issue by ROpdebee** [Homebrew/homebrew-cask-versions#8083]
`firefox-beta` and `firefox-developer-edition` are unversioned casks, whereas `firefox-esr` is versioned.

Relevant PRs: #5095, #5061

To me, it does not make much sense that they're unversioned. A full list of versions can be found [here](https://download-installer.cdn.mozilla.net/pub/firefox/releases/), and a potential appcast could be obtained by following the redirect.

What's the limitation that I'm not aware of? I'm guessing this has something to do with `cask-repair` being unable to repair casks with language stanzas, thus discouraging users from actively contributing updates.

**Comment by vitorgalvao** [comment]
The language stanzas together with the frequent updates are the issue, yes.

https://github.com/Homebrew/homebrew-cask-versions/pull/5061#issuecomment-355818783
