### ISSUE TITLE
On outdated betas and pre-releases

### ISSUE THREAD

**Issue by ROpdebee** [Homebrew/homebrew-cask-versions#8098]
Feel free to close this and point me to an existing resource if something along these lines has already been discussed before. I've done some research and couldn't find anything though (but I might be dumb).

# Motivation
Let's start with a couple of concrete examples:
- [`iina-beta`](https://github.com/Homebrew/homebrew-cask-versions/blob/dc8539744e0bfc82ce5265e5a30b87aa35fb9344/Casks/iina-beta.rb): No new beta release for 11 months. Current stable release is at 1.0.4, released half a year ago. [(source)](https://iina.io/download/)
- [`krita-dev`](https://github.com/Homebrew/homebrew-cask-versions/blob/dc8539744e0bfc82ce5265e5a30b87aa35fb9344/Casks/krita-dev.rb): Current stable is 4.2.7.1, latest beta is 4.2.7-beta1 (two weeks older). [(source)](https://krita.org/en/download/krita-desktop/), [(source')](https://download.kde.org/unstable/krita/)
- [`ghidra-beta`](https://github.com/Homebrew/homebrew-cask-versions/blob/dc8539744e0bfc82ce5265e5a30b87aa35fb9344/Casks/ghidra-beta.rb): Current stable is 9.1, release Oct. 23, whereas the beta is released Sept. 23, but only added a couple days ago. [(source)](https://www.ghidra-sre.org/releaseNotes_9.1_final.html)

I'm sure there some other examples currently, and there will continue to be such cases.

Ultimately, the question I want to raise is: What to do with the outdated beta releases in this tap? Thus, the intent is to spark a discussion regarding this. Ideally, we should make it possible for users to always receive the latest version of their desired app, while inducing minimal overhead for maintainers.

Over the past couple of days, I've assembled a number of rough approaches that *may* be viable. Being a long-time user of Homebrew Cask and the versions tap, a (small-time) contributor to multiple Homebrew repositories, and having been a maintainer of a comparable project long ago, I feel that I'm in a reasonable position to evaluate these approaches from different points-of-view, yet I encourage you to review these thoroughly, provide criticism where needed, and extend and/or suggest ideas.

Three main factors of evaluation:
- User experience: Not getting stuck on old betas (e.g.: I did not realize there was a new version of IINA that was not a beta for a couple of months), not having to switch between two different casks, ...
- Maintainers (short-term): Short-term maintenance, like changing the backend or cleaning up the casks, is to be avoided as much as possible.
- Maintainers (long-term): Continuous/regular monitoring would add to the already large work package of maintainers.

# Approaches
### Idea
After x number of months of a stable release, remove the beta if no new beta has been released.
### Effect
All the above examples are removed, either "now" or in due time.

### Maintenance effort (short-term)
**Medium**: Find casks that haven't been changed in x months and review for cleanup.
### Maintenance effort (long-term)
**High**: Requires periodic checkups of cask health.
### User experience
**Bad**: Casks get removed and users need to change to another cask.

### Additional cons
- If a cask later gets new betas, it potentially needs to be re-added and re-reviewed.

### Idea
If a stable version gets released, also bump the pre-release cask to this stable release.
### Effect
All of the above examples are bumped to a stable version.

### Maintenance effort (short-term)
**Medium**: Needs review of the casks to check if there's a more up-to-date, stable release. Could be semi-automated by checking against the version in homebrew-cask.
### Maintenance effort (long-term)
**Medium to low**: Requires more updates, PRs, keeping in sync with homebrew-cask, ... Could be made to have low overhead if BrewTestBot could be made to automatically bump the pre-release version in this tap to the later, stable version in the homebrew-cask tap. However, this requires more short-term effort to update the bot.
### User experience
**Okay**: No cask switching required, users don't get stuck on old betas. However, this may lead to confusion if two casks have the same version.

### Additional cons
- **Duplication of information across different taps.**

### Idea
When  a user installs or upgrades a pre-release cask, the backend checks if the stable cask has a more recent version, and installs that instead. This corresponds to checking an option as "Allow updating to beta versions" in an updater for an app. In practice, the user still has installed a beta cask, but the system ensures a user always installs the latest version.
### Effect
None of the above casks are directly affected, but on install, the stable version is installed instead.

### Maintenance effort (short-term)
**High**: Requires significant changes in the backend, and potentially requires changing all casks to link to the stable version. I'd be willing to update the casks on my own, if someone is willing to change the backend.
### Maintenance effort (long-term)
**Low**: No periodic changes to casks required. Could be combined with approach 1 to remove betas that are not updated.
### User experience
**Good**: Transparent solution, the user is always on the latest cask and does not need to switch casks. Potential confusion when a beta cask installs a stable version though.

### Additional cons
- Potentially goes against the intents of this tap? Also impedes on the separation of concerns between taps.

# Wrap up
As both an avid user of brew cask, a user of beta versions, as well as a contributor to this repo, my vote goes out to the third approach. I'll gladly chip in where appropriate to make the supporting changes to better handle situations such as the ones given in the examples.

I would love to get some feedback and criticism on this topic, and am hoping to spark an extensive discussion. Looking forward to your feedback!

**Comment by vitorgalvao** [comment]
Approach **1** is what’s closer to what we do now (see [acceptable casks](https://github.com/Homebrew/homebrew-cask-versions#acceptable-casks)), though we’re not really checking. The script to auto-remove casks that were unchanged should be easy (I already have one that deletes casks with too few downloads) but it isn’t ideal due to old commercial versions.

There’s a fourth option: changing the backend to allow a flag to install a particular version of cask, then manage all versions inside the same file. That’s similar to **3**, but it doesn’t require a (possibly finicky) system to check what version is oldest, since it’s at times not obvious.

**Comment by ROpdebee** [comment]
> There’s a fourth option: changing the backend to allow a flag to install a particular version of cask, then manage all versions inside the same file.
I've always remembered that this tap was spawned specifically to not have to manage different versions in the same repo, let alone the same file, but I might (probably am) misremembering. Although from a UX standpoint I definitely think this may be the better idea, so there's 0 confusion with different versions, I think from a maintenance standpoint this may cause some issues. I'm thinking merge conflicts if the beta version and stable version get bumped simultaneously, etc.

> it doesn’t require a (possibly finicky) system to check what version is oldest, since it’s at times not obvious.
I agree that such a system could sporadically be finnicky, especially if no standard versioning scheme is used. I don't agree that such a system would not require version ordering, since it would still need to determine whether a beta is more recent than a stable release if betas are allowed, unless we shift the burden to the user and let them decide.

**Comment by vraravam** [comment]
I vote for option 3 - seems very good ROI with a contained effort (ie effort from a few people without compromising on the UX of the wider user-community).

If this is taken further, and since its ruby, i can volunteer to help.

**Comment by vitorgalvao** [comment]
Here’s another idea.

Casks don’t support aliases (like formulae do), but if they did, we could alias the (outdated) beta cask to the stable cask. That’s similar to **2** in effect, but there’s way less effort and no duplication.

That should be introduced in tandem with a `formula_renames.json` equivalent for casks, so that we could permanently redirect a stale beta (that we’re going to remove) to a stable version.
