### ISSUE TITLE
microsoft-remote-desktop-beta is broken

### ISSUE THREAD

**Issue by bb2020** [Homebrew/homebrew-cask-versions#8311]
#### General troubleshooting steps

Checksum fails while installing from latest Cask.
```n
Error: Checksum for Cask 'microsoft-remote-desktop-beta' does not match.
Expected: e1c9d863663ffb16677a7d7c28df0c7b3b5ba51e9db55e6381900503ced44623
  Actual: 908890fd77ad59f6cb3f5916dedbb6aab553d16f185ce2a6bf5c4cdf5937dca3
```
It is because `https://rink.hockeyapp.net/api/2/apps/5e0c144289a51fca2d3bfa39ce7f2b06/app_versions/417` always returns 10.3.1 as the newest version, not 10.3.7. I've tried other version numbers, but no luck. Maybe we should fetch a new URL using Wireshark.

- [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

**Comment by vitorgalvao** [comment]
Please don’t ignore the template.

All you need to fix this cask is on the `appcast`. https://github.com/Homebrew/homebrew-cask-versions/pull/8313/files
