### ISSUE TITLE
Upgrade Java11 cask from 11.0.2 to 11.0.6

### ISSUE THREAD

**Issue by ryanzJ2** [Homebrew/homebrew-cask-versions#8602]
Not a bug and not sure if related to issues [#57387](https://github.com/Homebrew/homebrew-cask/issues/57387).  Current Java 11 is not using the latest [JDK 11 release](https://www.oracle.com/technetwork/java/javase/11u-relnotes-5093844.html) and does not contain [tls backport fix](https://bugs.openjdk.java.net/browse/JDK-8210005) causing 
`javax.net.ssl.SSLHandshakeException` in some scenarios. I was able to verify java8 working but i'm not sure upgrading java11 version will fix my issue.

https://github.com/Homebrew/homebrew-cask-versions/blob/65c1ee4e66a8612bfe005cc607767f3422ee4d6b/Casks/java11.rb#L2

**Comment by vitorgalvao** [comment]
We’ll accept a PR to update the cask.
