### ISSUE TITLE
Add scene-builder for Java 8

### ISSUE THREAD

**Issue by jmborer** [Homebrew/homebrew-cask-versions#8752]
Please add the Java 8 version of Gluon Scene Builder. The standard one in Java 11.

https://gluonhq.com/products/scene-builder/

**Comment by vitorgalvao** [comment]
[From the README](https://github.com/Homebrew/homebrew-cask/#requests):

> Issues requesting new casks will be closed. If you want a cask added to the main repositories, [submit a pull request](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#adding-a-cask).

This is also explicit in [the issue templates](https://github.com/Homebrew/homebrew-cask/issues/new/choose), where the one clearly labeled `Cask Request` with the subtitle `For requesting new casks`, states the same thing.

Please do not ignore our templates or documentation.
