### ISSUE TITLE
Revert #4657 and add android-studio-beta

### ISSUE THREAD

**Issue by tir38** [Homebrew/homebrew-cask-versions#8993]
This isn't so much a request as it is a discussion for "is this a good idea?". I'm happy to do the work if enough people 👍 

TL;DR I want to revert https://github.com/Homebrew/homebrew-cask-versions/pull/4657 to move `android-studio-preview` back to `android-studio-canary` and add a separate cask: `android-studio-beta`

Reasons:

1. "preview" is actually a bit vague. I had to go through the history on that cask to see whether it was tracking canary or beta releases. At the time of the original PR there may have only been one "preview" channel but now they are distinct.

2. I think enough people want to use beta but don't want to commit to canary channels.

**Comment by vitorgalvao** [comment]
Don’t outright revert, as some of the other changes are good. But yes, you may rename it to `canary` and add a `beta`.
